# Topics
camera_topic: "/front_cam/image_raw"
camera_info: "/front_cam/camera_info"
lidar_topic: "/ouster/points"

# Dynamic rqt_reconfigure default bounds
feature_extraction:
  x_min: 1.8
  x_max: 2.8
  y_min: -1.6
  y_max: 0.96
  z_min: -0.1
  z_max: 1.8
  
# Properties of chessboard calibration target
chessboard:
  pattern_size:
    height: 7
    width: 5  
  square_length: 95
  board_dimension:
    width: 607
    height: 905
  translation_error:
    x: 6
    y: 1
